/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Process is up. This check does not query Postgres.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange email and password for a JWT
         * @description Returns a bearer token. Local databases seeded by `db/migrations`
         *     include `dev@ruehrai.local` / `dev-password`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user and return a JWT
         * @description Password hashing is done in Postgres (`pgcrypto` bcrypt) and the row is
         *     stored in `app.users`. Minimum password length is 8. The response matches
         *     `POST /auth/login`.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Requires Authorization: Bearer <accessToken>.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current access token
         * @description Requires `Authorization: Bearer <accessToken>`. Stores the token id
         *     (`jti`) in `app.revoked_tokens` until the token's own expiry. A later
         *     request with the same token is `401`. Clients should also drop the
         *     token locally. This is the Slice-1 session end: JWTs stay stateless
         *     apart from this denylist. There is no refresh token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/target-region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the signed-in user's target region
         * @description One region per user, the area where they want to open a new store.
         *     `404` when nothing has been saved yet.
         */
        get: operations["getTargetRegion"];
        /**
         * Create or replace the target region
         * @description Upserts the single region for the token's user. Omitted scalar geo
         *     fields are stored as null, including fields set by a previous save.
         *
         *     `bounds` and `geometry` are filled when the body omits them. A GeoJSON
         *     Polygon or MultiPolygon on the request is stored, and `bounds`
         *     (west, south, east, north) are derived from its coordinates. `bounds`
         *     without geometry become a rectangular Polygon. Otherwise the API copies
         *     a Polygon or MultiPolygon from `app.map_features` for the ags, plz, or
         *     geoKey, or builds a stub rectangle around the catalog point in
         *     `app.search_places` or a Point feature. Those outlines are the same
         *     synthetic stubs as `/layers/{id}`, not official boundaries.
         *
         *     `lon` and `lat` stay as sent when both are set. A polygon sent by the
         *     client uses its centroid when the pair is omitted. A catalog outline
         *     uses the catalog point when one exists, otherwise the geometry centroid.
         *     Web fits the map to store pins union `bounds`, and draws `geometry` as
         *     a semi-transparent fill with an outline. Labels are client-side.
         */
        put: operations["putTargetRegion"];
        post?: never;
        /**
         * Clear the target region
         * @description Idempotent. Responds `204` even when no region was stored.
         */
        delete: operations["deleteTargetRegion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in user's store addresses
         * @description A read persists `lon`/`lat` when the stored pair is null, or when an
         *     address match in Data-Scout replaces a pin that still sits on a PLZ
         *     centroid. An explicit pair is returned unchanged. Resolution order is
         *     the same as create.
         */
        get: operations["listStores"];
        put?: never;
        /**
         * Add a store address
         * @description German address (`postalCode` is PLZ5, `countryCode` is `DE`).
         *     `street` includes the house number. `lon` and `lat` are optional WGS84
         *     (EPSG:4326) for the map pin. Clients are not required to send them.
         *     Send both or neither. KAN-56 Option A, when both are omitted:
         *
         *     1. Data-Scout `geo_ref_address` (`strasse` + `hnr` parsed from `street`,
         *        plus `plz`). Berlin OSM coverage. This is the house-number pin.
         *     2. Data-Scout `geo_ref_plz` centroid, only when step 1 misses.
         *     3. PLZ centroid from `app.search_places`, then a Point in
         *        `app.map_features` with that PLZ, only when steps 1 and 2 miss.
         *
         *     Steps 1 and 2 run only when `DATASCOUT_DATABASE_URL` is set and the
         *     read succeeds. Otherwise the API uses step 3. Coordinates stay null
         *     only when none of the steps hit. No public geocoder is called.
         *     Update uses the same order. A pair sent by the client is stored
         *     unchanged; it is an optional override, not the primary source.
         *     A read persists a filled null pair, and replaces a stored PLZ centroid
         *     when step 1 hits.
         */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        /**
         * Read one store address
         * @description 404 when the id is missing or belongs to another user.
         */
        get: operations["getStore"];
        /**
         * Replace a store address
         * @description Same coordinate rule as create. Omit `lon` and `lat` together to
         *     resolve Data-Scout `geo_ref_address`, then `geo_ref_plz`, then the
         *     `app.search_places` / `app.map_features` PLZ stub. Send both to keep
         *     an explicit WGS84 pin.
         */
        put: operations["updateStore"];
        post?: never;
        /**
         * Delete a store address
         * @description Also deletes monthly revenue for that store.
         */
        delete: operations["deleteStore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{id}/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        /**
         * Monthly revenue for one store
         * @description Points the customer has saved, ordered by year then month. A point with
         *     `revenueEur: null` was explicitly marked missing. A month with no point
         *     was not entered. At most 36 points are stored per store.
         */
        get: operations["listStoreRevenue"];
        /**
         * Upsert monthly revenue points
         * @description Inserts or replaces each `(year, month)` in the body. Other saved months
         *     stay. `revenueEur: null` marks that month as missing. The store can hold
         *     at most 36 months; a request that would exceed that returns `400` and
         *     changes nothing.
         */
        put: operations["putStoreRevenue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{id}/revenue/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove one monthly revenue point
         * @description `204` when the store exists, including when that month was not stored.
         *     `404` when the store is missing or belongs to another user.
         */
        delete: operations["deleteStoreRevenueMonth"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search places by name, grain, or geo key
         * @description Reads `features.v_location_search` when that view contains at least one row.
         *     Filters apply to name, title, grain, and geo_key. `lon` and `lat` are
         *     JSON null when the row has no coordinates.
         *
         *     `q` is a substring. `type` limits `q` to grain `ags`, `plz5`/`plz8`, or
         *     `address`. Without `type`, `q` matches name, title, and geo_key.
         *     `type` has no effect when `q` is omitted.
         *
         *     `ags` and `plz` are exact geo_key matches on that grain. `geoKey` is an
         *     exact geo_key match on any grain. `grain` is exact. `address` is a
         *     substring of name, title, and geo_key. Filters combine with AND.
         *     At most 50 hits, ordered by label.
         *
         *     If the view is missing or has no rows (local docker-compose), the same
         *     filters run against the seeded `app.search_places` catalog.
         *     Coordinates are WGS84 (EPSG:4326) when present.
         */
        get: operations["searchPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GeoJSON FeatureCollection for a layer
         * @description Returns a GeoJSON FeatureCollection as `application/json`.
         *     Layer rows stay in schema `app` (`map_layers`, `map_features`) until
         *     feature documents have coordinates. Seeded layer ids in local dev:
         *     `demo-gemeinden`, `demo-plz`, `demo-grid100`.
         *     Geometries are synthetic stubs for this slice (points, plus one rough polygon),
         *     not official boundaries. Coordinates are WGS84 (EPSG:4326), longitude then latitude.
         */
        get: operations["getLayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Structured analysis input for the signed-in user
         * @description Builds the Musteranalyse input from the user's saved target region,
         *     store addresses, and monthly revenue (at most 36 months per store).
         *     A revenue change counts only between two successive calendar months
         *     that both have a non-null amount. `404` when no target region is
         *     saved. `400` when no store has two adjacent months with revenue.
         */
        get: operations["getAnalysisInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Snapshot input, search Brain, and persist a pattern
         * @description Same preconditions as `GET /analysis/input`. On success the run is
         *     stored for this user and includes the Brain facts used (region filter,
         *     plus store postal codes) and the derived pattern. The pattern is the
         *     input a later Top-3 step can read. This operation does not recommend
         *     addresses.
         */
        post: operations["createAnalysisRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one analysis run of the signed-in user */
        get: operations["getAnalysisRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/pattern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest persisted pattern for the signed-in user
         * @description Returns the pattern from the newest completed run. `404` when the
         *     user has not completed an analysis yet.
         */
        get: operations["getAnalysisPattern"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest recommendation set for the signed-in user
         * @description Returns the newest set stored by `POST /recommendations` for the token
         *     user. `404` when this user has not computed recommendations yet.
         */
        get: operations["getRecommendations"];
        put?: never;
        /**
         * Rank up to three locations for the signed-in user
         * @description Reads a completed Musteranalyse pattern for this user (the newest run,
         *     or `runId` when set) and searches Brain locations in the target region.
         *     A location ranks when at least one pattern criterion with a direction
         *     moved the same way inside the six UTC calendar months ending in the
         *     request month. Score is the share of those directional criteria that
         *     match. The response has at most three items, ordered by score.
         *
         *     One or two matches are success, not an error: `reason` explains the
         *     thin region in German. Zero matches are also success, with `reason`
         *     set and `items` empty. `404` when this user has no completed pattern,
         *     or when `runId` is not one of their runs.
         *
         *     The region anchor itself is omitted when a finer positive location
         *     exists. Finer grains match when their `geo_key` is under the region
         *     key or their metadata names the region (`geo_ags`, `ags`, `plz`,
         *     `geo_plz`, `geo_key`). Each item's `rationale` is German and grounded
         *     in `criteriaEvidence`. `source` is `llm` when that text came from the
         *     local model, otherwise `heuristic`.
         */
        post: operations["createRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Token lifetime in seconds.
             * @example 28800
             */
            expiresIn: number;
        };
        User: {
            /** @description User id as a decimal string. */
            id: string;
            /** Format: email */
            email: string;
        };
        /**
         * @description Spatial grain of a hit. Matches the Datenbasis grain list used by this slice.
         * @enum {string}
         */
        Grain: "address" | "grid100" | "plz8" | "plz5" | "ags" | "ags5" | "other";
        /** @enum {string} */
        SearchType: "address" | "ags" | "plz";
        SearchHit: {
            id: string;
            label: string;
            grain: components["schemas"]["Grain"];
            /** @description Spatial key from the feature view (AGS, PLZ, address id, or grid id). Null when unknown. */
            geoKey?: string | null;
            /**
             * Format: double
             * @description WGS84 longitude. Omitted or null when the hit is not geocoded.
             */
            lon?: number | null;
            /**
             * Format: double
             * @description WGS84 latitude. Omitted or null when the hit is not geocoded.
             */
            lat?: number | null;
        };
        SearchResponse: {
            hits: components["schemas"]["SearchHit"][];
        };
        /** @description GeoJSON geometry. This slice seeds Point and Polygon. */
        Geometry: {
            /** @enum {string} */
            type: "Point" | "Polygon" | "MultiPolygon";
            /** @description GeoJSON coordinates. Position order is longitude, latitude (EPSG:4326). */
            coordinates: unknown;
        } & {
            [key: string]: unknown;
        };
        Feature: {
            /** @enum {string} */
            type: "Feature";
            id?: string;
            geometry: components["schemas"]["Geometry"];
            /** @description Includes label, grain, and stub: true for seeded demo features. */
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * @description GeoJSON FeatureCollection. `name` and `description` are foreign members
         *     carried for this API (RFC 7946 allows them).
         */
        FeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            name?: string;
            description?: string;
            features: components["schemas"]["Feature"][];
        };
        /**
         * @description Axis-aligned WGS84 extent for map fitBounds. `west` and `east` are
         *     longitudes, `south` and `north` are latitudes. Clients union this box
         *     with store pin coordinates.
         */
        LonLatBounds: {
            /** Format: double */
            west: number;
            /** Format: double */
            south: number;
            /** Format: double */
            east: number;
            /** Format: double */
            north: number;
        };
        /**
         * @description GeoJSON Polygon or MultiPolygon for the target-region overlay
         *     (semi-transparent fill and outline). Position order is longitude,
         *     latitude (EPSG:4326). Rings are closed. This slice uses the same
         *     synthetic stubs as `/layers/{id}` when the client does not send one.
         */
        RegionGeometry: {
            /** @enum {string} */
            type: "Polygon" | "MultiPolygon";
            /** @description GeoJSON coordinates for the declared type. */
            coordinates: unknown;
        } & {
            [key: string]: unknown;
        };
        TargetRegion: {
            label: string;
            /**
             * @description Same values as Grain. Null when the region is a free-text label.
             * @enum {string|null}
             */
            grain?: "address" | "grid100" | "plz8" | "plz5" | "ags" | "ags5" | "other" | null;
            geoKey?: string | null;
            ags?: string | null;
            plz?: string | null;
            /**
             * Format: double
             * @description WGS84 longitude of a representative point. Null when unknown.
             */
            lon?: number | null;
            /**
             * Format: double
             * @description WGS84 latitude of a representative point. Null when unknown.
             */
            lat?: number | null;
            /**
             * @description Extent of `geometry` for map fitBounds. Null when the region has
             *     no outline and no catalog point.
             */
            bounds: components["schemas"]["LonLatBounds"] | null;
            /** @description Overlay polygon. Null when the region has no outline and no catalog point. */
            geometry: components["schemas"]["RegionGeometry"] | null;
            /** Format: date-time */
            updatedAt: string;
        };
        TargetRegionWrite: {
            label: string;
            /** @enum {string|null} */
            grain?: "address" | "grid100" | "plz8" | "plz5" | "ags" | "ags5" | "other" | null;
            geoKey?: string | null;
            ags?: string | null;
            plz?: string | null;
            /** Format: double */
            lon?: number | null;
            /** Format: double */
            lat?: number | null;
            /**
             * @description Optional extent. Stored as a rectangular Polygon when `geometry` is omitted.
             *     Ignored when `geometry` is set, because bounds are then derived from it.
             */
            bounds?: components["schemas"]["LonLatBounds"] | null;
            /**
             * @description Optional GeoJSON Polygon or MultiPolygon (EPSG:4326). When set, it is
             *     the overlay and replaces any catalog outline.
             */
            geometry?: components["schemas"]["RegionGeometry"] | null;
        };
        StoreLocation: {
            /** @description Store id as a decimal string. */
            id: string;
            /** @description Optional store name. */
            label?: string | null;
            /** @description Street and house number. */
            street: string;
            /** @description German PLZ5. */
            postalCode: string;
            city: string;
            /** @enum {string} */
            countryCode: "DE";
            /**
             * Format: double
             * @description WGS84 longitude for the map pin. Resolved, when a write omits both
             *     coordinates, from Data-Scout `geo_ref_address`, then `geo_ref_plz`,
             *     then the PLZ stub in `app.search_places` or `app.map_features`.
             */
            lon?: number | null;
            /**
             * Format: double
             * @description WGS84 latitude for the map pin. Resolved, when a write omits both
             *     coordinates, from Data-Scout `geo_ref_address`, then `geo_ref_plz`,
             *     then the PLZ stub in `app.search_places` or `app.map_features`.
             */
            lat?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StoreLocationWrite: {
            label?: string | null;
            street: string;
            postalCode: string;
            city: string;
            /**
             * @default DE
             * @enum {string}
             */
            countryCode: "DE";
            /**
             * Format: double
             * @description WGS84 longitude. Omit together with `lat` to resolve
             *     `geo_ref_address`, then `geo_ref_plz`, then the PLZ stub.
             */
            lon?: number | null;
            /**
             * Format: double
             * @description WGS84 latitude. Omit together with `lon` to resolve
             *     `geo_ref_address`, then `geo_ref_plz`, then the PLZ stub.
             */
            lat?: number | null;
        };
        StoreList: {
            stores: components["schemas"]["StoreLocation"][];
        };
        MonthlyRevenuePoint: {
            year: number;
            month: number;
            /**
             * Format: double
             * @description EUR. Null means the month was marked missing.
             */
            revenueEur: number | null;
            /** Format: date-time */
            updatedAt: string;
        };
        MonthlyRevenuePointWrite: {
            year: number;
            month: number;
            /** Format: double */
            revenueEur: number | null;
        };
        MonthlyRevenueSeries: {
            points: components["schemas"]["MonthlyRevenuePoint"][];
        };
        MonthlyRevenueWrite: {
            points: components["schemas"]["MonthlyRevenuePointWrite"][];
        };
        /**
         * @description Snapshot of customer inputs used for Musteranalyse. `stores[].points`
         *     holds up to 36 months. `changes` links only successive calendar months
         *     that both have a revenue.
         */
        AnalysisInput: {
            region: components["schemas"]["TargetRegion"];
            stores: components["schemas"]["AnalysisStore"][];
            revenueDirection: components["schemas"]["RevenueDirection"];
            /** Format: date-time */
            capturedAt: string;
        };
        AnalysisStore: {
            id: string;
            label?: string | null;
            street: string;
            postalCode: string;
            city: string;
            /** Format: double */
            lon?: number | null;
            /** Format: double */
            lat?: number | null;
            points: components["schemas"]["AnalysisRevenuePoint"][];
            changes: components["schemas"]["AnalysisRevenueChange"][];
        };
        AnalysisRevenuePoint: {
            year: number;
            month: number;
            /** Format: double */
            revenueEur: number | null;
        };
        AnalysisRevenueChange: {
            fromYear: number;
            fromMonth: number;
            toYear: number;
            toMonth: number;
            /** Format: double */
            fromRevenueEur: number;
            /** Format: double */
            toRevenueEur: number;
            /**
             * Format: double
             * @description toRevenueEur minus fromRevenueEur, rounded to cents.
             */
            changeEur: number;
        };
        /**
         * @description Sign of the summed month-to-month revenue changes. Flat means the sum is zero.
         * @enum {string}
         */
        RevenueDirection: "up" | "down" | "flat";
        /**
         * @description Direction of one Brain criterion. `unknown` means the facts do not
         *     show a change over time (often a single reference period).
         * @enum {string}
         */
        CriterionDirection: "up" | "down" | "flat" | "unknown";
        AnalysisRun: {
            /** @description Run id as a decimal string. */
            id: string;
            /** @enum {string} */
            status: "completed";
            /** Format: date-time */
            createdAt: string;
            input: components["schemas"]["AnalysisInput"];
            brain: components["schemas"]["AnalysisBrain"];
            pattern: components["schemas"]["AnalysisPattern"];
        };
        /**
         * @description Facts retrieved for this run. `vector` means cosine similarity over
         *     Brain embeddings, filtered to the target region and store postal
         *     codes. `sql` means the same filters without a vector (embeddings
         *     unset, unreachable, or not usable). This is not a raw Brain dump.
         */
        AnalysisBrain: {
            /** @enum {string} */
            mode: "vector" | "sql";
            /**
             * @description Why `mode` is `sql`. Null when `mode` is `vector`.
             * @enum {string|null}
             */
            vectorUnavailableReason?: "embeddings_disabled" | "embeddings_unconfigured" | "embeddings_unreachable" | "embeddings_rejected" | "vector_query_failed" | "no_embeddings_in_region" | "features_unavailable" | null;
            /** @description Number of facts included on this run. */
            factCount: number;
            facts: components["schemas"]["BrainFact"][];
        };
        BrainFact: {
            id: string;
            geoKey: string;
            grain: components["schemas"]["Grain"];
            title: string;
            name?: string | null;
            refPeriod?: string | null;
            /** @description Short prose from the feature document, or the title when no prose is stored. */
            excerpt: string;
            /**
             * Format: double
             * @description Cosine distance when mode is vector. Null for the SQL filter.
             */
            distance?: number | null;
            /**
             * @description `region` matches the target region ags, plz, or geoKey.
             *     `store` matches a store postal code.
             *     `label` is the text fallback when the region has no geo key.
             * @enum {string}
             */
            matchedBy: "region" | "store" | "label";
            signals: components["schemas"]["BrainSignal"][];
        };
        BrainSignal: {
            key: string;
            value: string;
        };
        /**
         * @description Persisted pattern for a later Top-3 step. `source` is `llm` when the
         *     criteria were taken from the language model and checked against the
         *     retrieved facts, otherwise `heuristic`.
         */
        AnalysisPattern: {
            /** @enum {string} */
            source: "llm" | "heuristic";
            summary: string;
            revenueDirection: components["schemas"]["RevenueDirection"];
            criteria: components["schemas"]["PatternCriterion"][];
        };
        PatternCriterion: {
            key: string;
            label: string;
            direction: components["schemas"]["CriterionDirection"];
            /** @description Grounded in the retrieved Brain facts or the stored revenue series. */
            evidence: string;
        };
        AnalysisPatternResponse: {
            runId: string;
            /** Format: date-time */
            createdAt: string;
            pattern: components["schemas"]["AnalysisPattern"];
        };
        /**
         * @description Optional body for `POST /recommendations`. Omit `runId` to use the
         *     newest completed analysis run of the token user.
         */
        RecommendationCreate: {
            /** @description Analysis run id as a decimal string. Must belong to the token user. */
            runId?: string;
        };
        /**
         * @description Top-3 payload the web client binds to. `count` is `items.length` and
         *     is never greater than 3. `reason` is null when three positive locations
         *     were available. `pattern` is the snapshot used for this ranking.
         */
        RecommendationSet: {
            /** @description Recommendation set id as a decimal string. */
            id: string;
            /** @description Analysis run this set was ranked from. */
            runId: string;
            /** Format: date-time */
            createdAt: string;
            window: components["schemas"]["RecommendationWindow"];
            count: number;
            /**
             * @description German explanation when fewer than three locations are returned,
             *     or when the Brain read hit its row limit. Null when three matches
             *     were ranked without truncation.
             */
            reason: string | null;
            pattern: components["schemas"]["AnalysisPattern"];
            items: components["schemas"]["Recommendation"][];
        };
        /**
         * @description Six calendar months, inclusive, ending in the UTC month of the request.
         *     Brain `ref_period` values outside this window do not affect the score.
         */
        RecommendationWindow: {
            /**
             * @description Oldest month in the window (`YYYY-MM`).
             * @example 2026-04
             */
            from: string;
            /**
             * @description Newest month in the window (`YYYY-MM`).
             * @example 2026-09
             */
            to: string;
        };
        Recommendation: {
            /**
             * @description Stable location id `{grain}:{geoKey}` inside this set.
             * @example plz5:80801
             */
            id: string;
            rank: number;
            /** @description Card title. Place name, address line, or geo key from Brain. */
            title: string;
            location: components["schemas"]["RecommendationLocation"];
            /**
             * Format: double
             * @description Share of pattern criteria that have a direction and moved the same
             *     way at this location inside the window. 1 is a full fit.
             */
            score: number;
            /**
             * @description German Begründung. Names only criteria and figures present in
             *     `criteriaEvidence`.
             */
            rationale: string;
            criteriaEvidence: components["schemas"]["RecommendationEvidence"][];
            /**
             * @description `llm` when `rationale` was taken from the local model and checked
             *     against `criteriaEvidence`. `heuristic` when the model was unset,
             *     failed, or its text was discarded.
             * @enum {string}
             */
            source: "llm" | "heuristic";
        };
        RecommendationLocation: {
            geoKey: string;
            grain: components["schemas"]["Grain"];
            /** Format: double */
            lon: number | null;
            /** Format: double */
            lat: number | null;
            /** @description Brain place name when the row has one. */
            name: string | null;
        };
        /**
         * @description One pattern criterion that moved in the pattern direction at this
         *     location. `direction` is what Brain shows in the window.
         *     `patternDirection` is the saved Musteranalyse direction.
         */
        RecommendationEvidence: {
            key: string;
            label: string;
            direction: components["schemas"]["CriterionDirection"];
            patternDirection: components["schemas"]["CriterionDirection"];
            /** @description German sentence with the months and figures used for the score. */
            evidence: string;
        };
        ErrorResponse: {
            statusCode?: number;
            message?: string | string[];
            error?: string;
        };
    };
    responses: {
        /** @description Request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Store id as a decimal string. */
        StoreId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "dev@ruehrai.local",
                 *       "password": "dev-password"
                 *     }
                 */
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown email or wrong password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description User created and signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User row for the token subject. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked. The body is empty. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The token has no revocable id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTargetRegion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved target region. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRegion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description This user has not saved a target region. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putTargetRegion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "label": "München",
                 *       "grain": "ags",
                 *       "geoKey": "09162000",
                 *       "ags": "09162000",
                 *       "lon": 11.5755,
                 *       "lat": 48.1374
                 *     }
                 */
                "application/json": components["schemas"]["TargetRegionWrite"];
            };
        };
        responses: {
            /** @description Saved target region. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRegion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteTargetRegion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target region cleared. The body is empty. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listStores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stores owned by the token's user, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "label": "Filiale Marienplatz",
                 *       "street": "Marienplatz 1",
                 *       "postalCode": "80331",
                 *       "city": "München"
                 *     }
                 */
                "application/json": components["schemas"]["StoreLocationWrite"];
            };
        };
        responses: {
            /** @description Store created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreLocation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store owned by the token's user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreLocation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreLocationWrite"];
            };
        };
        responses: {
            /** @description Updated store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreLocation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store deleted. The body is empty. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listStoreRevenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved months. Empty `points` when none have been entered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyRevenueSeries"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putStoreRevenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "points": [
                 *         {
                 *           "year": 2025,
                 *           "month": 1,
                 *           "revenueEur": 18450.5
                 *         },
                 *         {
                 *           "year": 2025,
                 *           "month": 2,
                 *           "revenueEur": null
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["MonthlyRevenueWrite"];
            };
        };
        responses: {
            /** @description Full series after the upsert. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyRevenueSeries"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStoreRevenueMonth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store id as a decimal string. */
                id: components["parameters"]["StoreId"];
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Month removed, or it was not stored. The body is empty. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No store with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchPlaces: {
        parameters: {
            query?: {
                /** @description Free-text substring. Interpretation depends on `type`. */
                q?: string;
                /** @description Field that `q` is matched against. Ignored when `q` is absent. */
                type?: components["schemas"]["SearchType"];
                /** @description Substring matched against the address and the label. */
                address?: string;
                /** @description Exact Amtlicher Gemeindeschlüssel (2–8 digits). */
                ags?: string;
                /** @description Exact PLZ5 or PLZ8. */
                plz?: string;
                /** @description Exact geo_key on any grain. */
                geoKey?: string;
                /** @description Exact spatial grain. */
                grain?: components["schemas"]["Grain"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching hits, at most 50, ordered by label. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "hits": [
                     *         {
                     *           "id": "1",
                     *           "label": "München",
                     *           "grain": "ags",
                     *           "geoKey": "09162000",
                     *           "lon": null,
                     *           "lat": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example demo-gemeinden */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer contents. An existing layer with no features returns an empty `features` array. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "FeatureCollection",
                     *       "name": "Demo-Gemeinden",
                     *       "description": "Synthetische Demo-Geometrien.",
                     *       "features": [
                     *         {
                     *           "type": "Feature",
                     *           "id": "ags:11000000",
                     *           "geometry": {
                     *             "type": "Point",
                     *             "coordinates": [
                     *               13.405,
                     *               52.52
                     *             ]
                     *           },
                     *           "properties": {
                     *             "label": "Berlin",
                     *             "grain": "ags",
                     *             "ags": "11000000",
                     *             "stub": true
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No layer with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAnalysisInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Input that a run would snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisInput"];
                };
            };
            /** @description Region exists, but monthly revenue is not sufficient. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": "Die Monatsumsätze reichen für eine Musteranalyse nicht aus. Mindestens eine Filiale braucht zwei aufeinanderfolgende Monate mit gesetztem Umsatz.",
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description This user has not saved a target region. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Keine Zielregion gespeichert. Bitte zuerst eine Zielregion anlegen.",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createAnalysisRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed analysis run. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            /** @description Monthly revenue is not sufficient for a pattern. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description This user has not saved a target region. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAnalysisRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run id as a decimal string. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run, including input, Brain facts, and pattern. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No run with this id for the token's user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Die Analyse wurde nicht gefunden.",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAnalysisPattern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest pattern. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisPatternResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No completed analysis run for this user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Es liegt noch kein Muster vor. Bitte zuerst eine Analyse starten.",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest recommendation set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationSet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description This user has no stored recommendations. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Es liegen noch keine Empfehlungen vor. Bitte zuerst Empfehlungen berechnen.",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecommendationCreate"];
            };
        };
        responses: {
            /** @description Persisted recommendation set for this user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3",
                     *       "runId": "15",
                     *       "createdAt": "2026-09-29T12:00:00.000Z",
                     *       "window": {
                     *         "from": "2026-04",
                     *         "to": "2026-09"
                     *       },
                     *       "count": 1,
                     *       "reason": "In der Zielregion liegt nur 1 Standort mit positiver Musterentwicklung in den letzten sechs Monaten vor.",
                     *       "pattern": {
                     *         "source": "heuristic",
                     *         "summary": "Einwohner steigen mit dem Umsatz.",
                     *         "revenueDirection": "up",
                     *         "criteria": [
                     *           {
                     *             "key": "einwohner",
                     *             "label": "einwohner",
                     *             "direction": "up",
                     *             "evidence": "einwohner steigt zwischen den vorliegenden Zeiträumen."
                     *           }
                     *         ]
                     *       },
                     *       "items": [
                     *         {
                     *           "id": "plz5:80801",
                     *           "rank": 1,
                     *           "title": "Schwabing",
                     *           "location": {
                     *             "geoKey": "80801",
                     *             "grain": "plz5",
                     *             "lon": 11.58,
                     *             "lat": 48.16,
                     *             "name": "Schwabing"
                     *           },
                     *           "score": 1,
                     *           "rationale": "Am Standort Schwabing (80801) passt das Muster in den letzten sechs Monaten. Quelle: Heuristik, ohne Sprachmodell.",
                     *           "criteriaEvidence": [
                     *             {
                     *               "key": "einwohner",
                     *               "label": "einwohner",
                     *               "direction": "up",
                     *               "patternDirection": "up",
                     *               "evidence": "einwohner steigt in den letzten sechs Monaten (2026-04: 10; 2026-09: 20)."
                     *             }
                     *           ],
                     *           "source": "heuristic"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RecommendationSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No completed analysis pattern for this user, or the run id is not theirs. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
