/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Process is up. This check does not query Postgres.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange email and password for a JWT
         * @description Returns a bearer token. Local databases seeded by `db/migrations`
         *     include `dev@ruehrai.local` / `dev-password`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user and return a JWT
         * @description Password hashing is done in Postgres (`pgcrypto` bcrypt). Minimum password length is 8.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Requires Authorization: Bearer <accessToken>.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search places by name, grain, or geo key
         * @description Reads `features.v_location_search` when that view contains at least one row.
         *     Filters apply to name, title, grain, and geo_key. `lon` and `lat` are
         *     JSON null when the row has no coordinates.
         *
         *     `q` is a substring. `type` limits `q` to grain `ags`, `plz5`/`plz8`, or
         *     `address`. Without `type`, `q` matches name, title, and geo_key.
         *     `type` has no effect when `q` is omitted.
         *
         *     `ags` and `plz` are exact geo_key matches on that grain. `geoKey` is an
         *     exact geo_key match on any grain. `grain` is exact. `address` is a
         *     substring of name, title, and geo_key. Filters combine with AND.
         *     At most 50 hits, ordered by label.
         *
         *     If the view is missing or has no rows (local docker-compose), the same
         *     filters run against the seeded `app.search_places` catalog.
         *     Coordinates are WGS84 (EPSG:4326) when present.
         */
        get: operations["searchPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GeoJSON FeatureCollection for a layer
         * @description Returns a GeoJSON FeatureCollection as `application/json`.
         *     Layer rows stay in schema `app` (`map_layers`, `map_features`) until
         *     feature documents have coordinates. Seeded layer ids in local dev:
         *     `demo-gemeinden`, `demo-plz`, `demo-grid100`.
         *     Geometries are synthetic stubs for this slice (points, plus one rough polygon),
         *     not official boundaries. Coordinates are WGS84 (EPSG:4326), longitude then latitude.
         */
        get: operations["getLayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Token lifetime in seconds.
             * @example 28800
             */
            expiresIn: number;
        };
        User: {
            /** @description User id as a decimal string. */
            id: string;
            /** Format: email */
            email: string;
        };
        /**
         * @description Spatial grain of a hit. Matches the Datenbasis grain list used by this slice.
         * @enum {string}
         */
        Grain: "address" | "grid100" | "plz8" | "plz5" | "ags" | "ags5" | "other";
        /** @enum {string} */
        SearchType: "address" | "ags" | "plz";
        SearchHit: {
            id: string;
            label: string;
            grain: components["schemas"]["Grain"];
            /** @description Spatial key from the feature view (AGS, PLZ, address id, or grid id). Null when unknown. */
            geoKey?: string | null;
            /**
             * Format: double
             * @description WGS84 longitude. Omitted or null when the hit is not geocoded.
             */
            lon?: number | null;
            /**
             * Format: double
             * @description WGS84 latitude. Omitted or null when the hit is not geocoded.
             */
            lat?: number | null;
        };
        SearchResponse: {
            hits: components["schemas"]["SearchHit"][];
        };
        /** @description GeoJSON geometry. This slice seeds Point and Polygon. */
        Geometry: {
            /** @enum {string} */
            type: "Point" | "Polygon" | "MultiPolygon";
            /** @description GeoJSON coordinates. Position order is longitude, latitude (EPSG:4326). */
            coordinates: unknown;
        } & {
            [key: string]: unknown;
        };
        Feature: {
            /** @enum {string} */
            type: "Feature";
            id?: string;
            geometry: components["schemas"]["Geometry"];
            /** @description Includes label, grain, and stub: true for seeded demo features. */
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * @description GeoJSON FeatureCollection. `name` and `description` are foreign members
         *     carried for this API (RFC 7946 allows them).
         */
        FeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            name?: string;
            description?: string;
            features: components["schemas"]["Feature"][];
        };
        ErrorResponse: {
            statusCode?: number;
            message?: string | string[];
            error?: string;
        };
    };
    responses: {
        /** @description Request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "dev@ruehrai.local",
                 *       "password": "dev-password"
                 *     }
                 */
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown email or wrong password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description User created and signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User row for the token subject. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchPlaces: {
        parameters: {
            query?: {
                /** @description Free-text substring. Interpretation depends on `type`. */
                q?: string;
                /** @description Field that `q` is matched against. Ignored when `q` is absent. */
                type?: components["schemas"]["SearchType"];
                /** @description Substring matched against the address and the label. */
                address?: string;
                /** @description Exact Amtlicher Gemeindeschlüssel (2–8 digits). */
                ags?: string;
                /** @description Exact PLZ5 or PLZ8. */
                plz?: string;
                /** @description Exact geo_key on any grain. */
                geoKey?: string;
                /** @description Exact spatial grain. */
                grain?: components["schemas"]["Grain"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching hits, at most 50, ordered by label. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "hits": [
                     *         {
                     *           "id": "1",
                     *           "label": "München",
                     *           "grain": "ags",
                     *           "geoKey": "09162000",
                     *           "lon": null,
                     *           "lat": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example demo-gemeinden */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer contents. An existing layer with no features returns an empty `features` array. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "FeatureCollection",
                     *       "name": "Demo-Gemeinden",
                     *       "description": "Synthetische Demo-Geometrien.",
                     *       "features": [
                     *         {
                     *           "type": "Feature",
                     *           "id": "ags:11000000",
                     *           "geometry": {
                     *             "type": "Point",
                     *             "coordinates": [
                     *               13.405,
                     *               52.52
                     *             ]
                     *           },
                     *           "properties": {
                     *             "label": "Berlin",
                     *             "grain": "ags",
                     *             "ags": "11000000",
                     *             "stub": true
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No layer with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
