import Foundation

/// Backend surface the first iOS slice calls.
///
/// `MockAPIClient` implements this today. When `packages/api-contracts` publishes
/// OpenAPI v0, replace the mock with a client generated by `swift-openapi-generator`.
/// The app talks to the Backend only. Do not add a Supabase SDK.
public protocol RuehrAPIClient: Sendable {
    func health() async throws -> HealthResponse
    func search(query: String) async throws -> [SearchHit]
    func layer(id: String) async throws -> GeoJSONFeatureCollection
}
